### ISSUE TITLE
Extractos Existentes

### ISSUE THREAD

**Issue by matudelatower** [hcdposadas/hcd#10]
Migrar todos los `extractosTemario` y `extractoOrdenDelDia` que esten en `Expediente.php` por extracto al BAE y OD correspondiente.

**Comment by raulneis** [comment]
### Actualización del extracto de los proyectos del BAE
Se copia de `expediente.extracto_temario` a `proyecto_b_a_e.extracto`.
```sql
UPDATE proyecto_b_a_e
SET extracto = (SELECT e.extracto_temario FROM expediente e WHERE e.id = expediente_id)
WHERE extracto IS NULL
```

### Actualización del extracto de los dictámentes del OD
Se copia de `expediente.extracto_dictamen` (arriba dice extractoOrdenDelDia, pero está mal) a `dictamen_o_d.extracto`.
```sql
UPDATE dictamen_o_d
SET extracto = (SELECT e.extracto_dictamen FROM expediente e WHERE e.id = expediente_id)
WHERE extracto IS NULL
```
